### ISSUE TITLE
Access denied by hltv / cloudflare

### ISSUE THREAD

**Issue by joshuajeschek** [joshuajeschek/harold#7]
An error occurred while running the command: ```Error: Access denied | www.hltv.org used Cloudflare to restrict access```
command /ranking teams
right after starting
observer this, catch it

trace:
> at C:\Users\joshu\Documents\Projects\2021\harold\node_modules\hltv\lib\utils.js:73:27
    at step (C:\Users\joshu\Documents\Projects\2021\harold\node_modules\hltv\lib\utils.js:52:23)
    at Object.next (C:\Users\joshu\Documents\Projects\2021\harold\node_modules\hltv\lib\utils.js:33:53)
    at fulfilled (C:\Users\joshu\Documents\Projects\2021\harold\node_modules\hltv\lib\utils.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by joshuajeschek** [comment]
hasn't happened yet in rewrite
